// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: paxos.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	SenderLease   uint64                 `protobuf:"varint,2,opt,name=sender_lease,json=senderLease,proto3" json:"sender_lease,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *PrepareMessage) GetSenderLease() uint64 {
	if x != nil {
		return x.SenderLease
	}
	return 0
}

func (x *PrepareMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type PromiseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	SenderLease   uint64                 `protobuf:"varint,2,opt,name=sender_lease,json=senderLease,proto3" json:"sender_lease,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Ack           bool                   `protobuf:"varint,4,opt,name=ack,proto3" json:"ack,omitempty"`
	LastGoodRound uint64                 `protobuf:"varint,5,opt,name=last_good_round,json=lastGoodRound,proto3" json:"last_good_round,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PromiseMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *PromiseMessage) GetSenderLease() uint64 {
	if x != nil {
		return x.SenderLease
	}
	return 0
}

func (x *PromiseMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PromiseMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *PromiseMessage) GetLastGoodRound() uint64 {
	if x != nil {
		return x.LastGoodRound
	}
	return 0
}

func (x *PromiseMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	SenderLease   uint64                 `protobuf:"varint,2,opt,name=sender_lease,json=senderLease,proto3" json:"sender_lease,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptMessage) GetSenderLease() uint64 {
	if x != nil {
		return x.SenderLease
	}
	return 0
}

func (x *AcceptMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	SenderLease   uint64                 `protobuf:"varint,2,opt,name=sender_lease,json=senderLease,proto3" json:"sender_lease,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Ack           bool                   `protobuf:"varint,4,opt,name=ack,proto3" json:"ack,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptedMessage) GetSenderLease() uint64 {
	if x != nil {
		return x.SenderLease
	}
	return 0
}

func (x *AcceptedMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptedMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AcceptedMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\"d\n" +
	"\x0ePrepareMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12!\n" +
	"\fsender_lease\x18\x02 \x01(\x04R\vsenderLease\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\"\xb4\x01\n" +
	"\x0ePromiseMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12!\n" +
	"\fsender_lease\x18\x02 \x01(\x04R\vsenderLease\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x10\n" +
	"\x03ack\x18\x04 \x01(\bR\x03ack\x12&\n" +
	"\x0flast_good_round\x18\x05 \x01(\x04R\rlastGoodRound\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\"y\n" +
	"\rAcceptMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12!\n" +
	"\fsender_lease\x18\x02 \x01(\x04R\vsenderLease\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x8d\x01\n" +
	"\x0fAcceptedMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12!\n" +
	"\fsender_lease\x18\x02 \x01(\x04R\vsenderLease\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x10\n" +
	"\x03ack\x18\x04 \x01(\bR\x03ack\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value2d\n" +
	"\x05Paxos\x12-\n" +
	"\aPrepare\x12\x0f.PrepareMessage\x1a\x0f.PromiseMessage\"\x00\x12,\n" +
	"\x06Accept\x12\x0e.AcceptMessage\x1a\x10.AcceptedMessage\"\x00B\bZ\x06./mainb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paxos_proto_goTypes = []any{
	(*PrepareMessage)(nil),  // 0: PrepareMessage
	(*PromiseMessage)(nil),  // 1: PromiseMessage
	(*AcceptMessage)(nil),   // 2: AcceptMessage
	(*AcceptedMessage)(nil), // 3: AcceptedMessage
}
var file_paxos_proto_depIdxs = []int32{
	0, // 0: Paxos.Prepare:input_type -> PrepareMessage
	2, // 1: Paxos.Accept:input_type -> AcceptMessage
	1, // 2: Paxos.Prepare:output_type -> PromiseMessage
	3, // 3: Paxos.Accept:output_type -> AcceptedMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
