// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: grpc.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Revision      *uint64                `protobuf:"varint,3,opt,name=revision,proto3,oneof" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Action) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *Action) GetRevision() uint64 {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return 0
}

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type WriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReply) Reset() {
	*x = WriteReply{}
	mi := &file_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReply) ProtoMessage() {}

func (x *WriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReply.ProtoReflect.Descriptor instead.
func (*WriteReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteReply) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ReadRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequestMessage) Reset() {
	*x = ReadRequestMessage{}
	mi := &file_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestMessage) ProtoMessage() {}

func (x *ReadRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestMessage.ProtoReflect.Descriptor instead.
func (*ReadRequestMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequestMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReply) Reset() {
	*x = ReadReply{}
	mi := &file_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReply) ProtoMessage() {}

func (x *ReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReply.ProtoReflect.Descriptor instead.
func (*ReadReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *ReadReply) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ReadReply) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ReadRevisionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRevisionReply) Reset() {
	*x = ReadRevisionReply{}
	mi := &file_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRevisionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRevisionReply) ProtoMessage() {}

func (x *ReadRevisionReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRevisionReply.ProtoReflect.Descriptor instead.
func (*ReadRevisionReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRevisionReply) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *PrepareMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type PromiseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID and round unnecessary because promise is a reply to a prepare
	LastGoodRound uint64    `protobuf:"varint,1,opt,name=last_good_round,json=lastGoodRound,proto3" json:"last_good_round,omitempty"`
	Ack           bool      `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Proposal      *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3,oneof" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *PromiseMessage) GetLastGoodRound() uint64 {
	if x != nil {
		return x.LastGoodRound
	}
	return 0
}

func (x *PromiseMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *PromiseMessage) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Proposal      *Proposal              `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptMessage) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	SenderId      uint64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptedMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptedMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptedMessage) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type PromotionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        uint64                 `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionReply) Reset() {
	*x = PromotionReply{}
	mi := &file_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionReply) ProtoMessage() {}

func (x *PromotionReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionReply.ProtoReflect.Descriptor instead.
func (*PromotionReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *PromotionReply) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

type State struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitedPaxosId uint64                 `protobuf:"varint,1,opt,name=commited_paxos_id,json=commitedPaxosId,proto3" json:"commited_paxos_id,omitempty"`
	MinPaxosId      uint64                 `protobuf:"varint,2,opt,name=min_paxos_id,json=minPaxosId,proto3" json:"min_paxos_id,omitempty"`
	MaxPaxosId      uint64                 `protobuf:"varint,3,opt,name=max_paxos_id,json=maxPaxosId,proto3" json:"max_paxos_id,omitempty"`
	DataState       *Proposal              `protobuf:"bytes,4,opt,name=data_state,json=dataState,proto3" json:"data_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *State) GetCommitedPaxosId() uint64 {
	if x != nil {
		return x.CommitedPaxosId
	}
	return 0
}

func (x *State) GetMinPaxosId() uint64 {
	if x != nil {
		return x.MinPaxosId
	}
	return 0
}

func (x *State) GetMaxPaxosId() uint64 {
	if x != nil {
		return x.MaxPaxosId
	}
	return 0
}

func (x *State) GetDataState() *Proposal {
	if x != nil {
		return x.DataState
	}
	return nil
}

type CommitedPaxosID struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitedPaxosId uint64                 `protobuf:"varint,1,opt,name=commited_paxos_id,json=commitedPaxosId,proto3" json:"commited_paxos_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitedPaxosID) Reset() {
	*x = CommitedPaxosID{}
	mi := &file_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitedPaxosID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitedPaxosID) ProtoMessage() {}

func (x *CommitedPaxosID) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitedPaxosID.ProtoReflect.Descriptor instead.
func (*CommitedPaxosID) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *CommitedPaxosID) GetCommitedPaxosId() uint64 {
	if x != nil {
		return x.CommitedPaxosId
	}
	return 0
}

type KeyRev struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRev) Reset() {
	*x = KeyRev{}
	mi := &file_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRev) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRev) ProtoMessage() {}

func (x *KeyRev) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRev.ProtoReflect.Descriptor instead.
func (*KeyRev) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *KeyRev) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyRev) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type KeyRevsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyrevs       []*KeyRev              `protobuf:"bytes,1,rep,name=keyrevs,proto3" json:"keyrevs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRevsList) Reset() {
	*x = KeyRevsList{}
	mi := &file_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRevsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRevsList) ProtoMessage() {}

func (x *KeyRevsList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRevsList.ProtoReflect.Descriptor instead.
func (*KeyRevsList) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *KeyRevsList) GetKeyrevs() []*KeyRev {
	if x != nil {
		return x.Keyrevs
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OmitDeleted   bool                   `protobuf:"varint,1,opt,name=omitDeleted,proto3" json:"omitDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_grpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{16}
}

func (x *ListRequest) GetOmitDeleted() bool {
	if x != nil {
		return x.OmitDeleted
	}
	return false
}

type FillInProposalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillInProposalMessage) Reset() {
	*x = FillInProposalMessage{}
	mi := &file_grpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillInProposalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillInProposalMessage) ProtoMessage() {}

func (x *FillInProposalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillInProposalMessage.ProtoReflect.Descriptor instead.
func (*FillInProposalMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{17}
}

func (x *FillInProposalMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *FillInProposalMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_grpc_proto protoreflect.FileDescriptor

const file_grpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grpc.proto\x1a\x1bgoogle/protobuf/empty.proto\"m\n" +
	"\x06Action\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x1f\n" +
	"\brevision\x18\x03 \x01(\x04H\x01R\brevision\x88\x01\x01B\b\n" +
	"\x06_valueB\v\n" +
	"\t_revision\"-\n" +
	"\bProposal\x12!\n" +
	"\aactions\x18\x01 \x03(\v2\a.ActionR\aactions\"B\n" +
	"\n" +
	"WriteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"&\n" +
	"\x12ReadRequestMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\tReadReply\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevisionB\b\n" +
	"\x06_value\"/\n" +
	"\x11ReadRevisionReply\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"A\n" +
	"\x0ePrepareMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\"\x83\x01\n" +
	"\x0ePromiseMessage\x12&\n" +
	"\x0flast_good_round\x18\x01 \x01(\x04R\rlastGoodRound\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12*\n" +
	"\bproposal\x18\x03 \x01(\v2\t.ProposalH\x00R\bproposal\x88\x01\x01B\v\n" +
	"\t_proposal\"g\n" +
	"\rAcceptMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12%\n" +
	"\bproposal\x18\x03 \x01(\v2\t.ProposalR\bproposal\"\"\n" +
	"\x0eAcceptResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"_\n" +
	"\x0fAcceptedMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x04R\bsenderId\"(\n" +
	"\x0ePromotionReply\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\x04R\x06leader\"\xa1\x01\n" +
	"\x05State\x12*\n" +
	"\x11commited_paxos_id\x18\x01 \x01(\x04R\x0fcommitedPaxosId\x12 \n" +
	"\fmin_paxos_id\x18\x02 \x01(\x04R\n" +
	"minPaxosId\x12 \n" +
	"\fmax_paxos_id\x18\x03 \x01(\x04R\n" +
	"maxPaxosId\x12(\n" +
	"\n" +
	"data_state\x18\x04 \x01(\v2\t.ProposalR\tdataState\"=\n" +
	"\x0fCommitedPaxosID\x12*\n" +
	"\x11commited_paxos_id\x18\x01 \x01(\x04R\x0fcommitedPaxosId\"6\n" +
	"\x06KeyRev\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"0\n" +
	"\vKeyRevsList\x12!\n" +
	"\akeyrevs\x18\x01 \x03(\v2\a.KeyRevR\akeyrevs\"/\n" +
	"\vListRequest\x12 \n" +
	"\vomitDeleted\x18\x01 \x01(\bR\vomitDeleted\"H\n" +
	"\x15FillInProposalMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round2\xd5\x02\n" +
	"\x05Paxos\x12-\n" +
	"\aPrepare\x12\x0f.PrepareMessage\x1a\x0f.PromiseMessage\"\x00\x12+\n" +
	"\x06Accept\x12\x0e.AcceptMessage\x1a\x0f.AcceptResponse\"\x00\x126\n" +
	"\bAccepted\x12\x10.AcceptedMessage\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\x12SuggestPromoteSelf\x12\x16.google.protobuf.Empty\x1a\x0f.PromotionReply\"\x00\x12@\n" +
	"\x12GetCommitedPaxosID\x12\x16.google.protobuf.Empty\x1a\x10.CommitedPaxosID\"\x00\x125\n" +
	"\x0eFillInProposal\x12\x16.FillInProposalMessage\x1a\t.Proposal\"\x002\x99\x02\n" +
	"\x0eLeaderRequests\x12'\n" +
	"\rWriteToLeader\x12\a.Action\x1a\v.WriteReply\"\x00\x123\n" +
	"\x0eReadFromLeader\x12\x13.ReadRequestMessage\x1a\n" +
	".ReadReply\"\x00\x12C\n" +
	"\x16ReadRevisionFromLeader\x12\x13.ReadRequestMessage\x1a\x12.ReadRevisionReply\"\x00\x122\n" +
	"\x12ReadListFromLeader\x12\f.ListRequest\x1a\f.KeyRevsList\"\x00\x120\n" +
	"\fRequestState\x12\x16.google.protobuf.Empty\x1a\x06.State\"\x00B\vZ\t./clusterb\x06proto3"

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData []byte
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)))
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_grpc_proto_goTypes = []any{
	(*Action)(nil),                // 0: Action
	(*Proposal)(nil),              // 1: Proposal
	(*WriteReply)(nil),            // 2: WriteReply
	(*ReadRequestMessage)(nil),    // 3: ReadRequestMessage
	(*ReadReply)(nil),             // 4: ReadReply
	(*ReadRevisionReply)(nil),     // 5: ReadRevisionReply
	(*PrepareMessage)(nil),        // 6: PrepareMessage
	(*PromiseMessage)(nil),        // 7: PromiseMessage
	(*AcceptMessage)(nil),         // 8: AcceptMessage
	(*AcceptResponse)(nil),        // 9: AcceptResponse
	(*AcceptedMessage)(nil),       // 10: AcceptedMessage
	(*PromotionReply)(nil),        // 11: PromotionReply
	(*State)(nil),                 // 12: State
	(*CommitedPaxosID)(nil),       // 13: CommitedPaxosID
	(*KeyRev)(nil),                // 14: KeyRev
	(*KeyRevsList)(nil),           // 15: KeyRevsList
	(*ListRequest)(nil),           // 16: ListRequest
	(*FillInProposalMessage)(nil), // 17: FillInProposalMessage
	(*emptypb.Empty)(nil),         // 18: google.protobuf.Empty
}
var file_grpc_proto_depIdxs = []int32{
	0,  // 0: Proposal.actions:type_name -> Action
	1,  // 1: PromiseMessage.proposal:type_name -> Proposal
	1,  // 2: AcceptMessage.proposal:type_name -> Proposal
	1,  // 3: State.data_state:type_name -> Proposal
	14, // 4: KeyRevsList.keyrevs:type_name -> KeyRev
	6,  // 5: Paxos.Prepare:input_type -> PrepareMessage
	8,  // 6: Paxos.Accept:input_type -> AcceptMessage
	10, // 7: Paxos.Accepted:input_type -> AcceptedMessage
	18, // 8: Paxos.SuggestPromoteSelf:input_type -> google.protobuf.Empty
	18, // 9: Paxos.GetCommitedPaxosID:input_type -> google.protobuf.Empty
	17, // 10: Paxos.FillInProposal:input_type -> FillInProposalMessage
	0,  // 11: LeaderRequests.WriteToLeader:input_type -> Action
	3,  // 12: LeaderRequests.ReadFromLeader:input_type -> ReadRequestMessage
	3,  // 13: LeaderRequests.ReadRevisionFromLeader:input_type -> ReadRequestMessage
	16, // 14: LeaderRequests.ReadListFromLeader:input_type -> ListRequest
	18, // 15: LeaderRequests.RequestState:input_type -> google.protobuf.Empty
	7,  // 16: Paxos.Prepare:output_type -> PromiseMessage
	9,  // 17: Paxos.Accept:output_type -> AcceptResponse
	18, // 18: Paxos.Accepted:output_type -> google.protobuf.Empty
	11, // 19: Paxos.SuggestPromoteSelf:output_type -> PromotionReply
	13, // 20: Paxos.GetCommitedPaxosID:output_type -> CommitedPaxosID
	1,  // 21: Paxos.FillInProposal:output_type -> Proposal
	2,  // 22: LeaderRequests.WriteToLeader:output_type -> WriteReply
	4,  // 23: LeaderRequests.ReadFromLeader:output_type -> ReadReply
	5,  // 24: LeaderRequests.ReadRevisionFromLeader:output_type -> ReadRevisionReply
	15, // 25: LeaderRequests.ReadListFromLeader:output_type -> KeyRevsList
	12, // 26: LeaderRequests.RequestState:output_type -> State
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	file_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_grpc_proto_msgTypes[4].OneofWrappers = []any{}
	file_grpc_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
