// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: paxos.proto

package paxos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paxos_Prepare_FullMethodName                = "/Paxos/Prepare"
	Paxos_Accept_FullMethodName                 = "/Paxos/Accept"
	Paxos_Accepted_FullMethodName               = "/Paxos/Accepted"
	Paxos_WriteToLeader_FullMethodName          = "/Paxos/WriteToLeader"
	Paxos_ReadFromLeader_FullMethodName         = "/Paxos/ReadFromLeader"
	Paxos_ReadRevisionFromLeader_FullMethodName = "/Paxos/ReadRevisionFromLeader"
	Paxos_ReadListFromLeader_FullMethodName     = "/Paxos/ReadListFromLeader"
	Paxos_SuggestPromoteSelf_FullMethodName     = "/Paxos/SuggestPromoteSelf"
	Paxos_RequestState_FullMethodName           = "/Paxos/RequestState"
	Paxos_GetCommitedPaxosID_FullMethodName     = "/Paxos/GetCommitedPaxosID"
)

// PaxosClient is the client API for Paxos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosClient interface {
	Prepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*PromiseMessage, error)
	Accept(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*AcceptResponse, error)
	Accepted(ctx context.Context, in *AcceptedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WriteToLeader(ctx context.Context, in *Action, opts ...grpc.CallOption) (*WriteReply, error)
	ReadFromLeader(ctx context.Context, in *ReadRequestMessage, opts ...grpc.CallOption) (*ReadReply, error)
	ReadRevisionFromLeader(ctx context.Context, in *ReadRequestMessage, opts ...grpc.CallOption) (*ReadRevisionReply, error)
	ReadListFromLeader(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*KeyRevsList, error)
	SuggestPromoteSelf(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PromotionReply, error)
	RequestState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*State, error)
	GetCommitedPaxosID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommitedPaxosID, error)
}

type paxosClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosClient(cc grpc.ClientConnInterface) PaxosClient {
	return &paxosClient{cc}
}

func (c *paxosClient) Prepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*PromiseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseMessage)
	err := c.cc.Invoke(ctx, Paxos_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Accept(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*AcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, Paxos_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) Accepted(ctx context.Context, in *AcceptedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paxos_Accepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) WriteToLeader(ctx context.Context, in *Action, opts ...grpc.CallOption) (*WriteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteReply)
	err := c.cc.Invoke(ctx, Paxos_WriteToLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) ReadFromLeader(ctx context.Context, in *ReadRequestMessage, opts ...grpc.CallOption) (*ReadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, Paxos_ReadFromLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) ReadRevisionFromLeader(ctx context.Context, in *ReadRequestMessage, opts ...grpc.CallOption) (*ReadRevisionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRevisionReply)
	err := c.cc.Invoke(ctx, Paxos_ReadRevisionFromLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) ReadListFromLeader(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*KeyRevsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyRevsList)
	err := c.cc.Invoke(ctx, Paxos_ReadListFromLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) SuggestPromoteSelf(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PromotionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromotionReply)
	err := c.cc.Invoke(ctx, Paxos_SuggestPromoteSelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) RequestState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*State, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(State)
	err := c.cc.Invoke(ctx, Paxos_RequestState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosClient) GetCommitedPaxosID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommitedPaxosID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitedPaxosID)
	err := c.cc.Invoke(ctx, Paxos_GetCommitedPaxosID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServer is the server API for Paxos service.
// All implementations must embed UnimplementedPaxosServer
// for forward compatibility.
type PaxosServer interface {
	Prepare(context.Context, *PrepareMessage) (*PromiseMessage, error)
	Accept(context.Context, *AcceptMessage) (*AcceptResponse, error)
	Accepted(context.Context, *AcceptedMessage) (*emptypb.Empty, error)
	WriteToLeader(context.Context, *Action) (*WriteReply, error)
	ReadFromLeader(context.Context, *ReadRequestMessage) (*ReadReply, error)
	ReadRevisionFromLeader(context.Context, *ReadRequestMessage) (*ReadRevisionReply, error)
	ReadListFromLeader(context.Context, *ListRequest) (*KeyRevsList, error)
	SuggestPromoteSelf(context.Context, *emptypb.Empty) (*PromotionReply, error)
	RequestState(context.Context, *emptypb.Empty) (*State, error)
	GetCommitedPaxosID(context.Context, *emptypb.Empty) (*CommitedPaxosID, error)
	mustEmbedUnimplementedPaxosServer()
}

// UnimplementedPaxosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosServer struct{}

func (UnimplementedPaxosServer) Prepare(context.Context, *PrepareMessage) (*PromiseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosServer) Accept(context.Context, *AcceptMessage) (*AcceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosServer) Accepted(context.Context, *AcceptedMessage) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Accepted not implemented")
}
func (UnimplementedPaxosServer) WriteToLeader(context.Context, *Action) (*WriteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteToLeader not implemented")
}
func (UnimplementedPaxosServer) ReadFromLeader(context.Context, *ReadRequestMessage) (*ReadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFromLeader not implemented")
}
func (UnimplementedPaxosServer) ReadRevisionFromLeader(context.Context, *ReadRequestMessage) (*ReadRevisionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadRevisionFromLeader not implemented")
}
func (UnimplementedPaxosServer) ReadListFromLeader(context.Context, *ListRequest) (*KeyRevsList, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadListFromLeader not implemented")
}
func (UnimplementedPaxosServer) SuggestPromoteSelf(context.Context, *emptypb.Empty) (*PromotionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestPromoteSelf not implemented")
}
func (UnimplementedPaxosServer) RequestState(context.Context, *emptypb.Empty) (*State, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestState not implemented")
}
func (UnimplementedPaxosServer) GetCommitedPaxosID(context.Context, *emptypb.Empty) (*CommitedPaxosID, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommitedPaxosID not implemented")
}
func (UnimplementedPaxosServer) mustEmbedUnimplementedPaxosServer() {}
func (UnimplementedPaxosServer) testEmbeddedByValue()               {}

// UnsafePaxosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosServer will
// result in compilation errors.
type UnsafePaxosServer interface {
	mustEmbedUnimplementedPaxosServer()
}

func RegisterPaxosServer(s grpc.ServiceRegistrar, srv PaxosServer) {
	// If the following call panics, it indicates UnimplementedPaxosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paxos_ServiceDesc, srv)
}

func _Paxos_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Prepare(ctx, req.(*PrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Accept(ctx, req.(*AcceptMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_Accepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).Accepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_Accepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).Accepted(ctx, req.(*AcceptedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_WriteToLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).WriteToLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_WriteToLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).WriteToLeader(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_ReadFromLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).ReadFromLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_ReadFromLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).ReadFromLeader(ctx, req.(*ReadRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_ReadRevisionFromLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).ReadRevisionFromLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_ReadRevisionFromLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).ReadRevisionFromLeader(ctx, req.(*ReadRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_ReadListFromLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).ReadListFromLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_ReadListFromLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).ReadListFromLeader(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_SuggestPromoteSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).SuggestPromoteSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_SuggestPromoteSelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).SuggestPromoteSelf(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_RequestState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).RequestState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_RequestState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).RequestState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paxos_GetCommitedPaxosID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServer).GetCommitedPaxosID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paxos_GetCommitedPaxosID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServer).GetCommitedPaxosID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Paxos_ServiceDesc is the grpc.ServiceDesc for Paxos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paxos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Paxos",
	HandlerType: (*PaxosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Paxos_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Paxos_Accept_Handler,
		},
		{
			MethodName: "Accepted",
			Handler:    _Paxos_Accepted_Handler,
		},
		{
			MethodName: "WriteToLeader",
			Handler:    _Paxos_WriteToLeader_Handler,
		},
		{
			MethodName: "ReadFromLeader",
			Handler:    _Paxos_ReadFromLeader_Handler,
		},
		{
			MethodName: "ReadRevisionFromLeader",
			Handler:    _Paxos_ReadRevisionFromLeader_Handler,
		},
		{
			MethodName: "ReadListFromLeader",
			Handler:    _Paxos_ReadListFromLeader_Handler,
		},
		{
			MethodName: "SuggestPromoteSelf",
			Handler:    _Paxos_SuggestPromoteSelf_Handler,
		},
		{
			MethodName: "RequestState",
			Handler:    _Paxos_RequestState_Handler,
		},
		{
			MethodName: "GetCommitedPaxosID",
			Handler:    _Paxos_GetCommitedPaxosID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
