// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: paxos.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalMessage) Reset() {
	*x = ProposalMessage{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalMessage) ProtoMessage() {}

func (x *ProposalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalMessage.ProtoReflect.Descriptor instead.
func (*ProposalMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProposalMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InitiatiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPaxosId   uint64                 `protobuf:"varint,1,opt,name=next_paxos_id,json=nextPaxosId,proto3" json:"next_paxos_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatiationRequest) Reset() {
	*x = InitiatiationRequest{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatiationRequest) ProtoMessage() {}

func (x *InitiatiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatiationRequest.ProtoReflect.Descriptor instead.
func (*InitiatiationRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatiationRequest) GetNextPaxosId() uint64 {
	if x != nil {
		return x.NextPaxosId
	}
	return 0
}

type ReadRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequestMessage) Reset() {
	*x = ReadRequestMessage{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestMessage) ProtoMessage() {}

func (x *ReadRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestMessage.ProtoReflect.Descriptor instead.
func (*ReadRequestMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequestMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *PrepareMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type PromiseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID and round unnecessary because promise is a reply to a prepare
	LastGoodRound uint64           `protobuf:"varint,1,opt,name=last_good_round,json=lastGoodRound,proto3" json:"last_good_round,omitempty"`
	Ack           bool             `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Proposal      *ProposalMessage `protobuf:"bytes,3,opt,name=proposal,proto3,oneof" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *PromiseMessage) GetLastGoodRound() uint64 {
	if x != nil {
		return x.LastGoodRound
	}
	return 0
}

func (x *PromiseMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *PromiseMessage) GetProposal() *ProposalMessage {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Proposal      *ProposalMessage       `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptMessage) GetProposal() *ProposalMessage {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Ack           bool                   `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Proposal      *ProposalMessage       `protobuf:"bytes,4,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptedMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptedMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptedMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AcceptedMessage) GetProposal() *ProposalMessage {
	if x != nil {
		return x.Proposal
	}
	return nil
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\x0fProposalMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\":\n" +
	"\x14InitiatiationRequest\x12\"\n" +
	"\rnext_paxos_id\x18\x01 \x01(\x04R\vnextPaxosId\"&\n" +
	"\x12ReadRequestMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"3\n" +
	"\fReadResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"A\n" +
	"\x0ePrepareMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\"\x8a\x01\n" +
	"\x0ePromiseMessage\x12&\n" +
	"\x0flast_good_round\x18\x01 \x01(\x04R\rlastGoodRound\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x121\n" +
	"\bproposal\x18\x03 \x01(\v2\x10.ProposalMessageH\x00R\bproposal\x88\x01\x01B\v\n" +
	"\t_proposal\"n\n" +
	"\rAcceptMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12,\n" +
	"\bproposal\x18\x03 \x01(\v2\x10.ProposalMessageR\bproposal\"\"\n" +
	"\x0eAcceptResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"\x82\x01\n" +
	"\x0fAcceptedMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\bR\x03ack\x12,\n" +
	"\bproposal\x18\x04 \x01(\v2\x10.ProposalMessageR\bproposal2\xdd\x01\n" +
	"\x05Paxos\x12-\n" +
	"\aPrepare\x12\x0f.PrepareMessage\x1a\x0f.PromiseMessage\"\x00\x12+\n" +
	"\x06Accept\x12\x0e.AcceptMessage\x1a\x0f.AcceptResponse\"\x00\x126\n" +
	"\bAccepted\x12\x10.AcceptedMessage\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\rInitiateRound\x12\x15.InitiatiationRequest\x1a\x16.google.protobuf.Empty\"\x00B\tZ\a./paxosb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_paxos_proto_goTypes = []any{
	(*ProposalMessage)(nil),      // 0: ProposalMessage
	(*InitiatiationRequest)(nil), // 1: InitiatiationRequest
	(*ReadRequestMessage)(nil),   // 2: ReadRequestMessage
	(*ReadResponse)(nil),         // 3: ReadResponse
	(*PrepareMessage)(nil),       // 4: PrepareMessage
	(*PromiseMessage)(nil),       // 5: PromiseMessage
	(*AcceptMessage)(nil),        // 6: AcceptMessage
	(*AcceptResponse)(nil),       // 7: AcceptResponse
	(*AcceptedMessage)(nil),      // 8: AcceptedMessage
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_paxos_proto_depIdxs = []int32{
	0, // 0: PromiseMessage.proposal:type_name -> ProposalMessage
	0, // 1: AcceptMessage.proposal:type_name -> ProposalMessage
	0, // 2: AcceptedMessage.proposal:type_name -> ProposalMessage
	4, // 3: Paxos.Prepare:input_type -> PrepareMessage
	6, // 4: Paxos.Accept:input_type -> AcceptMessage
	8, // 5: Paxos.Accepted:input_type -> AcceptedMessage
	1, // 6: Paxos.InitiateRound:input_type -> InitiatiationRequest
	5, // 7: Paxos.Prepare:output_type -> PromiseMessage
	7, // 8: Paxos.Accept:output_type -> AcceptResponse
	9, // 9: Paxos.Accepted:output_type -> google.protobuf.Empty
	9, // 10: Paxos.InitiateRound:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	file_paxos_proto_msgTypes[3].OneofWrappers = []any{}
	file_paxos_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
