// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: paxos.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Action) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type InitiatiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPaxosId   uint64                 `protobuf:"varint,1,opt,name=next_paxos_id,json=nextPaxosId,proto3" json:"next_paxos_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatiationRequest) Reset() {
	*x = InitiatiationRequest{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatiationRequest) ProtoMessage() {}

func (x *InitiatiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatiationRequest.ProtoReflect.Descriptor instead.
func (*InitiatiationRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatiationRequest) GetNextPaxosId() uint64 {
	if x != nil {
		return x.NextPaxosId
	}
	return 0
}

type ReadRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequestMessage) Reset() {
	*x = ReadRequestMessage{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestMessage) ProtoMessage() {}

func (x *ReadRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestMessage.ProtoReflect.Descriptor instead.
func (*ReadRequestMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequestMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReply) Reset() {
	*x = ReadReply{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReply) ProtoMessage() {}

func (x *ReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReply.ProtoReflect.Descriptor instead.
func (*ReadReply) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *ReadReply) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *PrepareMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type PromiseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID and round unnecessary because promise is a reply to a prepare
	LastGoodRound uint64    `protobuf:"varint,1,opt,name=last_good_round,json=lastGoodRound,proto3" json:"last_good_round,omitempty"`
	Ack           bool      `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Proposal      *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3,oneof" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *PromiseMessage) GetLastGoodRound() uint64 {
	if x != nil {
		return x.LastGoodRound
	}
	return 0
}

func (x *PromiseMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *PromiseMessage) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Proposal      *Proposal              `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptMessage) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaxosId       uint64                 `protobuf:"varint,1,opt,name=paxos_id,json=paxosId,proto3" json:"paxos_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Proposal      *Proposal              `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptedMessage) GetPaxosId() uint64 {
	if x != nil {
		return x.PaxosId
	}
	return 0
}

func (x *AcceptedMessage) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AcceptedMessage) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type PromotionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        uint64                 `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionReply) Reset() {
	*x = PromotionReply{}
	mi := &file_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionReply) ProtoMessage() {}

func (x *PromotionReply) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionReply.ProtoReflect.Descriptor instead.
func (*PromotionReply) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *PromotionReply) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

type State struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitedPaxosId uint64                 `protobuf:"varint,1,opt,name=commited_paxos_id,json=commitedPaxosId,proto3" json:"commited_paxos_id,omitempty"`
	MinPaxosId      uint64                 `protobuf:"varint,2,opt,name=min_paxos_id,json=minPaxosId,proto3" json:"min_paxos_id,omitempty"`
	MaxPaxosId      uint64                 `protobuf:"varint,3,opt,name=max_paxos_id,json=maxPaxosId,proto3" json:"max_paxos_id,omitempty"`
	DataState       *Proposal              `protobuf:"bytes,4,opt,name=data_state,json=dataState,proto3" json:"data_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *State) GetCommitedPaxosId() uint64 {
	if x != nil {
		return x.CommitedPaxosId
	}
	return 0
}

func (x *State) GetMinPaxosId() uint64 {
	if x != nil {
		return x.MinPaxosId
	}
	return 0
}

func (x *State) GetMaxPaxosId() uint64 {
	if x != nil {
		return x.MaxPaxosId
	}
	return 0
}

func (x *State) GetDataState() *Proposal {
	if x != nil {
		return x.DataState
	}
	return nil
}

type CommitedPaxosID struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitedPaxosId uint64                 `protobuf:"varint,1,opt,name=commited_paxos_id,json=commitedPaxosId,proto3" json:"commited_paxos_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitedPaxosID) Reset() {
	*x = CommitedPaxosID{}
	mi := &file_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitedPaxosID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitedPaxosID) ProtoMessage() {}

func (x *CommitedPaxosID) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitedPaxosID.ProtoReflect.Descriptor instead.
func (*CommitedPaxosID) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *CommitedPaxosID) GetCommitedPaxosId() uint64 {
	if x != nil {
		return x.CommitedPaxosId
	}
	return 0
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x06Action\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"-\n" +
	"\bProposal\x12!\n" +
	"\aactions\x18\x01 \x03(\v2\a.ActionR\aactions\":\n" +
	"\x14InitiatiationRequest\x12\"\n" +
	"\rnext_paxos_id\x18\x01 \x01(\x04R\vnextPaxosId\"&\n" +
	"\x12ReadRequestMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\tReadReply\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"A\n" +
	"\x0ePrepareMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\"\x83\x01\n" +
	"\x0ePromiseMessage\x12&\n" +
	"\x0flast_good_round\x18\x01 \x01(\x04R\rlastGoodRound\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12*\n" +
	"\bproposal\x18\x03 \x01(\v2\t.ProposalH\x00R\bproposal\x88\x01\x01B\v\n" +
	"\t_proposal\"g\n" +
	"\rAcceptMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12%\n" +
	"\bproposal\x18\x03 \x01(\v2\t.ProposalR\bproposal\"\"\n" +
	"\x0eAcceptResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"i\n" +
	"\x0fAcceptedMessage\x12\x19\n" +
	"\bpaxos_id\x18\x01 \x01(\x04R\apaxosId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12%\n" +
	"\bproposal\x18\x03 \x01(\v2\t.ProposalR\bproposal\"(\n" +
	"\x0ePromotionReply\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\x04R\x06leader\"\xa1\x01\n" +
	"\x05State\x12*\n" +
	"\x11commited_paxos_id\x18\x01 \x01(\x04R\x0fcommitedPaxosId\x12 \n" +
	"\fmin_paxos_id\x18\x02 \x01(\x04R\n" +
	"minPaxosId\x12 \n" +
	"\fmax_paxos_id\x18\x03 \x01(\x04R\n" +
	"maxPaxosId\x12(\n" +
	"\n" +
	"data_state\x18\x04 \x01(\v2\t.ProposalR\tdataState\"=\n" +
	"\x0fCommitedPaxosID\x12*\n" +
	"\x11commited_paxos_id\x18\x01 \x01(\x04R\x0fcommitedPaxosId2\xc7\x03\n" +
	"\x05Paxos\x12-\n" +
	"\aPrepare\x12\x0f.PrepareMessage\x1a\x0f.PromiseMessage\"\x00\x12+\n" +
	"\x06Accept\x12\x0e.AcceptMessage\x1a\x0f.AcceptResponse\"\x00\x126\n" +
	"\bAccepted\x12\x10.AcceptedMessage\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\rInitiateRound\x12\x15.InitiatiationRequest\x1a\x16.google.protobuf.Empty\"\x00\x123\n" +
	"\x0eReadFromLeader\x12\x13.ReadRequestMessage\x1a\n" +
	".ReadReply\"\x00\x12?\n" +
	"\x12SuggestPromoteSelf\x12\x16.google.protobuf.Empty\x1a\x0f.PromotionReply\"\x00\x120\n" +
	"\fRequestState\x12\x16.google.protobuf.Empty\x1a\x06.State\"\x00\x12@\n" +
	"\x12GetCommitedPaxosID\x12\x16.google.protobuf.Empty\x1a\x10.CommitedPaxosID\"\x00B\tZ\a./paxosb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_paxos_proto_goTypes = []any{
	(*Action)(nil),               // 0: Action
	(*Proposal)(nil),             // 1: Proposal
	(*InitiatiationRequest)(nil), // 2: InitiatiationRequest
	(*ReadRequestMessage)(nil),   // 3: ReadRequestMessage
	(*ReadReply)(nil),            // 4: ReadReply
	(*PrepareMessage)(nil),       // 5: PrepareMessage
	(*PromiseMessage)(nil),       // 6: PromiseMessage
	(*AcceptMessage)(nil),        // 7: AcceptMessage
	(*AcceptResponse)(nil),       // 8: AcceptResponse
	(*AcceptedMessage)(nil),      // 9: AcceptedMessage
	(*PromotionReply)(nil),       // 10: PromotionReply
	(*State)(nil),                // 11: State
	(*CommitedPaxosID)(nil),      // 12: CommitedPaxosID
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_paxos_proto_depIdxs = []int32{
	0,  // 0: Proposal.actions:type_name -> Action
	1,  // 1: PromiseMessage.proposal:type_name -> Proposal
	1,  // 2: AcceptMessage.proposal:type_name -> Proposal
	1,  // 3: AcceptedMessage.proposal:type_name -> Proposal
	1,  // 4: State.data_state:type_name -> Proposal
	5,  // 5: Paxos.Prepare:input_type -> PrepareMessage
	7,  // 6: Paxos.Accept:input_type -> AcceptMessage
	9,  // 7: Paxos.Accepted:input_type -> AcceptedMessage
	2,  // 8: Paxos.InitiateRound:input_type -> InitiatiationRequest
	3,  // 9: Paxos.ReadFromLeader:input_type -> ReadRequestMessage
	13, // 10: Paxos.SuggestPromoteSelf:input_type -> google.protobuf.Empty
	13, // 11: Paxos.RequestState:input_type -> google.protobuf.Empty
	13, // 12: Paxos.GetCommitedPaxosID:input_type -> google.protobuf.Empty
	6,  // 13: Paxos.Prepare:output_type -> PromiseMessage
	8,  // 14: Paxos.Accept:output_type -> AcceptResponse
	13, // 15: Paxos.Accepted:output_type -> google.protobuf.Empty
	13, // 16: Paxos.InitiateRound:output_type -> google.protobuf.Empty
	4,  // 17: Paxos.ReadFromLeader:output_type -> ReadReply
	10, // 18: Paxos.SuggestPromoteSelf:output_type -> PromotionReply
	11, // 19: Paxos.RequestState:output_type -> State
	12, // 20: Paxos.GetCommitedPaxosID:output_type -> CommitedPaxosID
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	file_paxos_proto_msgTypes[0].OneofWrappers = []any{}
	file_paxos_proto_msgTypes[4].OneofWrappers = []any{}
	file_paxos_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
